# Generated by Django 4.2.7 on 2023-11-17 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abertura', models.DateField()),
                ('situacao', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
                ('nome', models.CharField(max_length=100)),
                ('fantasia', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=14)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
